---
title: "data tidying"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = F, message = F}
library(dplyr)
library(tidyr)
```

Read in catch data from [Mike Byerly. Alaska commercial salmon catches by management region (1886- 1997). Gulf of Alaska Data Portal. df35b.304.2](https://knb.ecoinformatics.org/view/df35b.304.2)

```{r}
catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_df)
```


`select` the columns we need
`gather` to move from wide to long
`rename` to indicate units

```{r}
catch_clean <- catch_df %>% 
  #select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)
  select(-All, -notesRegCode) %>% 
  gather(key = "Species", value = "catch", -Region, -Year) %>% 
  rename(catch_thousands = catch)
tail(catch_clean)
```

```{r}
test  <- as.numeric(catch_clean$catch_thousands)
i <- which(is.na(test) == T)
catch_clean[i,]
print(i)
```

`mutate` to create a new catch column
fix typo in original data
coerce to numeric
multiply by 1000 to get catch

```{r}
catch_clean_mutated <- catch_clean %>%
  mutate(catch_thousands = ifelse(catch_thousands == 'I', 1, catch_thousands)) %>% 
  mutate(catch_thousands = as.numeric(catch_thousands)) %>% 
  mutate(catch = catch_thousands*1000)
  tail(catch_clean_mutated)
```

```{r}
catch_summarized <- catch_clean_mutated %>%
  group_by(Region, Species) %>%
  summarize(mean_catch = mean(catch), n_obs = n())
head(catch_summarized)
```

```{r}
catch_chinook <- catch_clean_mutated %>% 
  filter(Species == "Chinook") %>% 
  arrange(catch)
head(catch_chinook)
```
